# Generated by Django 3.1.3 on 2020-11-26 10:38

from django.db import migrations, models
import sportify_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=sportify_api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
